### ISSUE TITLE
Native JSON for slack messages

### ISSUE THREAD

**Issue by michael-rath** [ibm-cloud-docs/assistant#337]
Hello, Could you please provide an example how to send a Native JSON message to Slack using attachments? When I build a JSON with the Slack message builder and add this to "output.slack", it is not showing the message in Slack, using the Standard IBM connector. Thank you!

**Comment by michelle-miller** [comment]
yes, looks like we link from here https://cloud.ibm.com/docs/services/assistant?topic=assistant-dialog-responses-json#dialog-responses-json-native to Slack api doc that is outdated here: https://api.slack.com/docs/message-attachments. we might need to investigate which new approach we support.
