### ISSUE TITLE
List of values in @sys-date.festival

### ISSUE THREAD

**Issue by BellaDunnett** [ibm-cloud-docs/assistant#343]
Please can a list of values for the @sys-date.festival entity be added to the docs? Only several examples are given and they only seem relevant for the US. I'm looking for holidays relating to the UK, particularly bank holidays, so I'd like to know if these are included in the entity already. If not, I'd like to know which holidays are for future use. Thank you!

**Comment by michelle-miller** [comment]
I'm told we do not currently include bank holidays. (But, we will look into adding them.) And we might need to do a review of the festival names first, but will try to get the full list documented. Thanks for asking the question.

**Comment by michelle-miller** [comment]
Finally, we added a list of the supported holidays. https://cloud.ibm.com/docs/assistant?topic=assistant-sys-date-festivals
