### ISSUE TITLE
Creating Watson Assistant using Java programmtically

### ISSUE THREAD

**Issue by geniusKoder** [ibm-cloud-docs/assistant#348]
I have referred to this documentation, but it does not explain how to create a Watson Assistant using Java programmtically. It only explains how to create via the UI. Please do share if there is any documentation regarding creating an Assistant using Java. (Not creating workspace/skill but the assistant.) Thank you very much.

https://cloud.ibm.com/docs/services/assistant?topic=assistant-assistant-add#assistant-add-delete

**Comment by michelle-miller** [comment]
There is no way to perform the task programmatically at this point. That is why it is not documented. The v2 APIs are currently under development.
