### ISSUE TITLE
Ambiguous direction

### ISSUE THREAD

**Issue by saheedandrew** [ibm-cloud-docs/assistant#349]
Its not clear enough on where you have to go to download your skilled JSON file, it took a while trying to find it. It will be better if you specified that you had to go under versions then click the hamburger button and click export to do so

**Comment by michelle-miller** [comment]
Thanks for the feedback. We added a section to the version topic to cover how to download a version. And we link to the main downloading a skill topic to the version section. 
https://cloud.ibm.com/docs/services/assistant?topic=assistant-versions#versions-export
https://cloud.ibm.com/docs/services/assistant?topic=assistant-skill-dialog-add#skill-dialog-add-download
