### ISSUE TITLE
IBM dialog json format

### ISSUE THREAD

**Issue by Brianjoroge** [ibm-cloud-docs/assistant#350]
what is the generic format of a Q&A form of chatbot? eg Intent: what is your name? Response: My name is brian.... i have thousands of reddit data, and I want to write a python script to integrate it with the ibm json format

**Comment by michelle-miller** [comment]
does the information in this topic https://cloud.ibm.com/docs/services/assistant?topic=assistant-dialog-responses-json answer your question?

**Comment by Brianjoroge** [comment]
hello Michelle, that article does not really, for example the json below (as given)
{
  "output": {
    "generic":[
      {
        "response_type": "text",
        "values": [
          { "text": "Hello." },
          { "text": "Hi there." }
        ],
        "selection_policy": "random"
      }
    ]
  }
}

only specifies the responses... i would like to see the inclusion of the Question, to see the format

**Comment by michelle-miller** [comment]
here's a full example
{
  "input" : {
    "message_type" : "text",
    "text" : "Medium",
    "options" : {
      "alternate_intents" : false,
      "suggestion_only" : false,
      "debug" : true,
      "return_context" : true,
      "restart" : false
    },
    "intents" : null,
    "entities" : null,
    "suggestion_id" : null
  },
  "context" : {
    "global" : {
      "system" : {
        "user_id" : "MrCasa",
        "timezone" : "Europe/Madrid",
        "locale" : "es-es",
        "reference_time" : "2025-09-01T01:00:00.000Z",
        "integration" : {
          "integration_instance_id" : "BDD_Dialog",
          "name" : "BDD"
        }
      }
    }
  }
}
09-25 14:20:16 -  
09-25 14:20:16 - HTTP Response:
{
  "output" : {
    "generic" : [ {
      "response_type" : "text",
      "text" : "Let me make sure I've got this right. You'd like a Medium Swiss Mocha Ice Cream Frappe. Do I have that right?"
    } ],
    "debug" : {
      "nodes_visited" : [ {
        "dialog_node" : "PurchaseSize",
        "title" : "PurchaseSize",
        "conditions" : "@Sizes"
      }, {
        "dialog_node" : "PurchaseValidateAll",
        "title" : "PurchaseValidateAll",
        "conditions" : "$Type && $Flavor && $Size && $Vehicle"
      }, {
        "dialog_node" : "PurchaseValidateLiquid",
        "title" : "PurchaseValidateLiquid",
        "conditions" : "$Vehicle == \"Frappe\" || $Vehicle == \"Milkshake\" || $Vehicle == \"Egg Cream\""
      } ],
      "log_messages" : [ ]
    },
    "intents" : [ {
      "intent" : "OffTopic",
      "confidence" : 0.5654044389724732
    } ],
    "entities" : [ {
      "entity" : "Sizes",
      "location" : [ 0, 6 ],
      "value" : "Medium",
      "confidence" : 1
    } ]
  },
  "context" : {
    "global" : {
      "system" : {
        "locale" : "es-es",
        "reference_time" : "2025-09-01T01:00:00.000Z",
        "timezone" : "Europe/Madrid",
        "user_id" : "MrCasa",
        "integration" : {
          "integration_instance_id" : "BDD_Dialog",
          "name" : "BDD"
        },
        "turn_count" : 3
      }
    },
    "skills" : {
      "main skill" : {
        "user_defined" : {
          "Size" : "Medium",
          "Type" : "Ice Cream",
          "Sizes" : [ "Kid", "Small", "Medium", "Large" ],
          "Types" : [ "Frozen Yogurt", "Ice Cream", "Soft Serve", "Sorbet" ],
          "Flavor" : "Swiss Mocha",
          "Vehicle" : "Frappe",
          "Vehicles" : [ "Wafer Cone", "Large Cup", "Small Cup" ],
          "SorbetFlavors" : [ "Bananas & Cream", "Blood Orange" ],
          "IceCreamFlavors" : [ "Black Cherry", "Black Raspberry" ],
          "SoftServeFlavors" : [ "Chocolate", "Vanilla" ],
          "FrozenYogurtFlavors" : [ "Acai Blueberry", "Black Raspberry" ],
          "OrderText" : "Medium Swiss Mocha Ice Cream Frappe"
        },
        "system" : {
          "state" : "eyJzZXNzaW9uX...="
        }
      }
    }
  }
}
