### ISSUE TITLE
Problem in create session

### ISSUE THREAD

**Issue by scyyx1** [ibm-cloud-docs/assistant#355]
When I reset up the api key and assistant id successfully, I cannot create a session and be thrown by a forbidden exception.

**Comment by michelle-miller** [comment]
If you want to report a problem with the API service, please send feedback or open an issue with IBM Cloud. This repo is for Watson Assistant product documentation. If you found a problem in the product documentation, please provide more details so we can try to reproduce and fix it. Thanks.
