### ISSUE TITLE
Adding Turkish Language Support

### ISSUE THREAD

**Issue by kursattuncel** [ibm-cloud-docs/assistant#356]
Hi,

Are there any plans to add Turkish as a supported language? How can I add new language support to IBM Watson Assitant? I'd like to help on this issue in case needed.

Best Regards,
Yusuf Kursat Tuncel

**Comment by michelle-miller** [comment]
Hi Yusuf.
No near-term plans to add Turkish language support. But, I've shared your feedback with offering  management, so they are aware of the request. Thanks.
