### ISSUE TITLE
Dialog Depiction

### ISSUE THREAD

**Issue by FMGordillo** [ibm-cloud-docs/assistant#358]
Is there a way to create a depiction as shown **[here](https://cloud.ibm.com/docs/services/assistant?topic=assistant-dialog-depiction)**?

**Comment by michelle-miller** [comment]
yes, create a dialog. add nodes to the dialog tree. for the first node in the depiction, that's just a standard node with a text response. it has two child nodes that both condition on entities. for the second node, that is a node with slots enabled.

**Comment by FMGordillo** [comment]
Sorry, maybe I wasn't clear. I want to know if there's a tool that creates a **graphic** similar to the one in the link.

**Comment by michelle-miller** [comment]
ah. i used balsamiq to create the diagram.
