### ISSUE TITLE
dialog-evolution incorrect functional difference

### ISSUE THREAD

**Issue by francesca-gigante** [ibm-cloud-docs/assistant#360]
In dialog evolution page, section Key functional differences, I read:
- Context variables are scoped to the action that uses them.

There are 2 issues associated to this statement:
1. Is it correct? It seems that, lucky, this behaviour is not implemented. I tried to set a context variable in an action and I can use it in another action.
2. It is impossible to manage conversations without using context variable that can be shared across actions (i.e. customer profile, customer preferences and so on), so it should be preferrable that it will not be implemented at all.

**Comment by michelle-miller** [comment]
i think long term the plan is to support global context variables that can be set and used across actions and action-specific context variables that only apply for a given action (as documented). I didn't realize that the product doesn't actually apply action-scoped context variables yet.
