### ISSUE TITLE
Question about the connection with the IBM watson assistant using java

### ISSUE THREAD

**Issue by scyyx1** [ibm-cloud-docs/assistant#361]
When I download the sdk and add the jar to the path of the project, I still cannot find the class called "IamOptions" and "DialogRuntimeResponseGeneric". Therefore, both first and second example cannot run successfully. How to fix the problem?

**Comment by lpatino10** [comment]
What examples are you referring to? Also, `IamOptions` is a deprecated class that's not present in the latest version of the SDK. Which version of the SDK are you trying to download?

**Comment by scyyx1** [comment]
Sorry, It seems that the Chinese version of the website hasn't been updated. I looked through the original one, everything looks fine, the problem has been solved, thanks a lot

**Comment by lpatino10** [comment]
Glad to hear that!

**Comment by scyyx1** [comment]
One more question, when I copy the code from the session "Using API -- build client application ", I cannot access my projects directly, why is that
<img width="739" alt="Screen Shot 2020-01-29 at 7 54 22 PM" src="https://user-images.githubusercontent.com/57601377/73392389-a742ea80-42d1-11ea-9744-5e0cd1dca781.png">

**Comment by michelle-miller** [comment]
did you sort this issue out @scyyx1 ?
