### ISSUE TITLE
Problem with Watson Discovery

### ISSUE THREAD

**Issue by CUslar** [ibm-cloud-docs/assistant#372]
I try to analize two files, both of them has someting like 10.000 lines. One is a .csv and the other a .json.
The thing is that neither of them was analize by Discovery.  The two of them was upload two days ago and even now the draw of the machine analizing hte data was there but never end and show no error the program.

**Comment by michelle-miller** [comment]
sent message to the writers of the discovery doc. this issue is not related to watson assistant.

**Comment by NickyBleiel** [comment]
@CUslar csv is not a supported file type --see https://cloud.ibm.com/docs/discovery?topic=discovery-addcontent#adding-content-with-the-api-or-tooling.

You may want to check StackOverflow: http://stackoverflow.com/questions/tagged/watson-discovery and the WDC Slack channel: http://wdc-slack-inviter.mybluemix.net/?cm_mc_uid=38028774880415730612944&cm_mc_sid_50200000=47602751590501163264&_ga=2.129264905.48252258.1590498842-470067053.1578064014 for more information.
