### ISSUE TITLE
Broken javascript sample to load WA widget with custom context

### ISSUE THREAD

**Issue by xverges** [ibm-cloud-docs/assistant#374]
https://cloud.ibm.com/docs/assistant?topic=assistant-deploy-web-chat#deploy-web-chat-set-context

This code does not work. When it is executed (before the loading of the WA script), `loadWatsonAssistantChat` is still not a function

**Comment by xverges** [comment]
It also would help to have a comment specifying that `"main skill"` is a value that does not need to be configured. I changed to my main skill name :-)

**Comment by michelle-miller** [comment]
hi @xverges thanks for taking the time to create this issue. the example is now updated. and great suggestion about explaining 'main skill'. we added a note about that. thanks for your feedback!
