### ISSUE TITLE
Need to add an example for filter query on an empty JSON field

### ISSUE THREAD

**Issue by juliankamil** [ibm-cloud-docs/assistant#376]
There is no documentation on how to filter based on an empty JSON field.  My use case is to filter Watson Assistant logs to exclude all log entries where the `request.input.text` is an empty string.

Reference: https://cloud.ibm.com/docs/assistant?topic=assistant-filter-reference#filter-reference

**Comment by rrberry** [comment]
I'm told that negating an exact match with an empty string should work:

```
request.input.text::!""
```

I will add this example to the documentation.

**Comment by rrberry** [comment]
Topic has been updated with an example for non-empty input text.
