### ISSUE TITLE
There is no ` Irrelevance detection page`

### ISSUE THREAD

**Issue by tbrodbeck** [ibm-cloud-docs/assistant#377]
In the documentation (https://cloud.ibm.com/docs/assistant?topic=assistant-irrelevance-detection#irrelevance-detection-how-it-works) it says:
```markdown
2. From the skill menu, click Options.
3. On the Irrelevance detection page, choose Enhanced.
```

But in WA it looks like this:
![Screenshot 2020-07-06 at 15 20 04](https://user-images.githubusercontent.com/24418160/86597537-2c76ad80-bf9c-11ea-9efc-cdb43ef720e2.png)

My problem in a nutshell: How can I turn off the irrelevancy for certain utterances?

**Comment by michelle-miller** [comment]
![image](https://user-images.githubusercontent.com/17206748/86630546-f71d9000-bf9a-11ea-92fe-acaf3c076037.png)

**Comment by tbrodbeck** [comment]
Okay thanks for the clarification.
