### ISSUE TITLE
IBM Watson Assistant Integration with Zendesk

### ISSUE THREAD

**Issue by Annabelle7989** [ibm-cloud-docs/assistant#378]
Hi, @michelle-miller , I followed all the steps from this url:
https://cloud.ibm.com/docs/assistant?topic=assistant-deploy-zendesk#deploy-zendesk-task

But I was not able to integrate ibm watson with zendesk.

I'm not able to view ibm in visitors page in zendesk portal like it was supposed to happen as stated in the ibm document. Can you please help me with this?

I'm also not able to view the "access account" button in ibm

![Screenshot (116)](https://user-images.githubusercontent.com/56390083/87122237-1cafdf80-c2a2-11ea-8861-967214249b24.png)

**Comment by michelle-miller** [comment]
Hi Annabelle. Do you have a Zendesk Chat Enterprise plan?

**Comment by Annabelle7989** [comment]
Hi @michelle-miller , sorry, didn't had an intent in assistant which connects me to a live agent. Figured it out, thanks:)
