### ISSUE TITLE
(Doc) Getting started: Broken link

### ISSUE THREAD

**Issue by Chofoteddy** [ibm-cloud-docs/assistant#380]
The link published on [Getting started with Watson Assistant](https://cloud.ibm.com/docs/assistant?topic=assistant-getting-started#getting-started) of the resource group is broken, if click on it you will see the message "Sorry, this content isn't available".

![image](https://user-images.githubusercontent.com/1615875/89723289-db524300-d9b9-11ea-8eb7-29f73548c77c.png)

--

![image](https://user-images.githubusercontent.com/1615875/89723310-0b014b00-d9ba-11ea-916a-175b56f3e0fd.png)

**Comment by michelle-miller** [comment]
Thank you for letting us know! Just submitted a fix that should be published within the hour.
