### ISSUE TITLE
getting-started-tutorial - out of date

### ISSUE THREAD

**Issue by matjung** [ibm-cloud-docs/assistant#383]
https://cloud.ibm.com/docs/assistant?topic=assistant-getting-started#getting-started-tutorial

I hit the button Launch Watson Assistant for the first time.

I see a screen "My first skill" and the assistant wants to create an Intent.
In step 4 the "getting started tutorial" starts to write about Intents.
I guess step 1 to 3 have become obsolete as the assistant is executing them without human actions.
--> The tutorial requires a review

**Comment by michelle-miller** [comment]
The automatic creation does not always happen. So, we cannot remove the steps. The last line of Step 1 says:
If an assistant and skill are not created automatically, complete Steps 2 and 3. Otherwise, skip to Step 4: Add intents from a content catalog.
