### ISSUE TITLE
Error: Forbidden, 403

### ISSUE THREAD

**Issue by manjunathreddyweb** [ibm-cloud-docs/assistant#384]
Following the documentation on https://cloud.ibm.com/docs/assistant?topic=assistant-api-client&programming_language=python

Using the code under _**Communicating with the Watson Assistant service**_ fails to retrieve service

**Comment by michelle-miller** [comment]
Check whether you're using the right API key. Reference: https://cloud.ibm.com/docs/assistant?topic=assistant-faqs#faqs-getting-403
