### ISSUE TITLE
slack didn't show the search skill response

### ISSUE THREAD

**Issue by Krascal** [ibm-cloud-docs/assistant#385]
Hello, I create a watson assistant with dialog and search skills. When trigger the anything else condition in the dialog, they will search the answer from watson discovery. I integrated this watson assistant with slack and preview link. I can get the feedback of search skills result from the preview link. And I also can get any other dialogs response in the slack. But I can't get any response in the slack when my question triggered the search skill. I can see that there is a response from search skill in the analytics of the watson assistant. So can you answer me why I can't see the response in the slack? Is there some settings wrong?

**Comment by michelle-miller** [comment]
sorry, this is not a documentation issue. sounds more like a problem with the product performance. This is not the right place to provide the feedback.

**Comment by ricknobrega** [comment]
Hi @Krascal,

Did you solved it in anyway please?
I'm facing same issue....
Messages arriving at Watson Analytics, but no answer in Slack :(

Thanks.
