### ISSUE TITLE
It's possible to include the max length of a condition in DialogNode Documentation?

### ISSUE THREAD

**Issue by ralphg6** [ibm-cloud-docs/assistant#387]
I am doing an implementation and I could avoid an errors if knew the max length of condition field on Dialog Node.

**Comment by michelle-miller** [comment]
The condition you define must be less than 2,048 characters in length.
from https://cloud.ibm.com/docs/assistant?topic=assistant-dialog-overview#dialog-overview-task

**Comment by ralphg6** [comment]
Thanks!!!
