### ISSUE TITLE
Need to include "addProperty" method

### ISSUE THREAD

**Issue by ahnugent** [ibm-cloud-docs/assistant#390]
I just wasted an hour searching for documentation on how to add a key-value pair to an existing context variable. I finally hit on the "addProperty" method by trial and error! 

Please include this and any other missing methods. (Nb. The Gson JsonObject documentation referred to a method called "add", which threw an exception, so it seems that this API is not 1:1 compatible.)

**Comment by michelle-miller** [comment]
We don't document every possible method. We support and document a subset (of the methods we think most people might find useful in the context of a dialog). I'm updating the methods topic to clarify that we support "some of the" methods that are available with Gson JsonObject.

**Comment by ahnugent** [comment]
Thanks, Michelle

That ought to avoid some confusion, at least.

Cheers,
Allen
