### ISSUE TITLE
Need to specify what webhooks options are available in each Assistant plan

### ISSUE THREAD

**Issue by dtoczala** [ibm-cloud-docs/assistant#394]
On most of the other documentation topics, if a feature is limited to use in just the Plus plan, or just the private plan, some sort of mention is made of it.  I don't see that with the help for the webhooks (https://cloud.ibm.com/docs/assistant?topic=assistant-webhook-overview)

**Comment by michelle-miller** [comment]
the logging webhook is the only one that you can't access from the Lite plan. it is documented as such.
https://cloud.ibm.com/docs/assistant?topic=assistant-webhook-log
