### ISSUE TITLE
IBM Watson Assistant  - Passing values to Zendesk Integration

### ISSUE THREAD

**Issue by shidobecker** [ibm-cloud-docs/assistant#398]
I followed all steps listed here to integrate IBM Watson Assistant to Zendesk
https://cloud.ibm.com/docs/assistant?topic=assistant-deploy-zendesk#deploy-zendesk-routing

But I'm struggling to find exactly how am I suppose to pass values to Zendesk. The information provided is not clear enough, and if I request an agent, there's no information about the user, it shows in zendesk like this:
![Screen Shot 2021-04-12 at 11 08 10](https://user-images.githubusercontent.com/13834922/114408935-4de67480-9b80-11eb-8525-da26358b8148.png)

The documentation says:

> Specify the information by using the following syntax. Use the exact names (name and email) for the two name and value pairs.
> 
> 
> {
> user_payload : {  
>          name: '#{customerName}',
>          email: '#{customerEmail}'
>   }
> }

And after that:

> Decide whether to allow unidentified users to access Zendesk.
> 
> The web chat integration allows anonymous users to initiate chats. However, as soon as you enable visitor authentication, Zendesk requires that the name and email of each user be provided. If you try to connect without passing the required information, the connection will be refused.
> 
> If you want to allow anonymous users to connect to Zendesk, you can provide fictitious name and email data. Write a function to populate the two fields with fictitious name and email values.
> 
> For example, your function must check whether you know the name and email of the current user, and if not, add canned values for them:
> 
> 
> const userPayload = {
>  "name" : "Jane Doe1",
>  "email" : "jdoe1@example.com",
> }

In my case, since users will access the assistant through a webview in an Android app, I have both name and email, and I don't need a whole authentication steps, all I want is to pass to zendesk those values, but can't exactly figure it out how. In the example, it just sets this constant but I don't know what to do with it, is there any code examples for it?

Thanks in advance

**Comment by AbdullahTasleem** [comment]
I have the same issue, I am sending the user payload as requested but always see the anonymous name and empty email address field. Any luck in figuring this out?

**Comment by californiakat** [comment]
our docs for Integrating with Zendesk with watsonx Assistant have been updated and can now be found at https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-deploy-zendesk
