### ISSUE TITLE
Need a New FAQ on Webhook IP Ranges

### ISSUE THREAD

**Issue by miltatibm** [ibm-cloud-docs/assistant#400]
We need a new FAQ about questions about Webhook ip ranges
Question: Is there a range of ip addresses that are being used by a Webhook?
Answer: Unfortunately, the IP address ranges from which Watson Assistant may call a webhook URL are subject to change which in turn prevent using them in any static firewall configuration.  Please use the https transport and specify an Authorization header to control access to the webhook.

**Comment by crlordan** [comment]
The Assistant FAQ topic has been updated: https://cloud.ibm.com/docs/assistant?topic=assistant-faqs
