### ISSUE TITLE
errors in web chat need more info in order to debug jsonwebtoken

### ISSUE THREAD

**Issue by jgsmals** [ibm-cloud-docs/assistant#402]
After consciously following the directions in https://cloud.ibm.com/docs/assistant?topic=assistant-web-chat-security#web-chat-security-task , I still cannot seem to make things work.

- An example is lacking about the configuration of a jsonwebtoken service and parameters therein, e.g. about key formatting: PEM, PPK, newline removal, "----- BEGIN SSH KEY -----" header removal or not, etc.  This is not necessarily trivial, for example using fastify the defaults need to be overridden:
```
fastify.register(require('fastify-jwt'), {
  secret: {
    private: process.env.MY_PRIVATEKEY,
    public: process.env.MY_PUBLICKEY 
  },
  sign: { 
    algorithm: 'RS256',
    expiresIn: 10000
  }
})
```
with keys encoded in the .env file in a oneliner form: `MY_PUBLICKEY=$'-----BEGIN PUBLIC KEY-----\nMIIBI...`

- I keep getting `A request for a new identity token was made using the identityTokenExpired event but no valid token was returned by a subscriber.` error, without any further information. My token seems to correctly encode, it decodes back as:
```
{
  sub: 'anonymous_IBMuid-f8776d3e-09ab-42aa-acc1-302f5b7be219',
  iss: 'mylittleproject.glitch.me',  
  iat: 1622022045,
  exp: 1622032045
}
```
With an error message like above I cannot debug further.

- I do not see why in the web chat security example `event.identityToken = 'YOUR NEW JWT'` is used, while a method `instance.updateIdentityToken(newtoken);` exists.

All help clearing this out is appreciated!

**Comment by californiakat** [comment]
docs for watsonx Assistant web chat security has been updated and moved to https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-web-chat-security
