### ISSUE TITLE
New FAQ for Monthly Active Users

### ISSUE THREAD

**Issue by miltatibm** [ibm-cloud-docs/assistant#403]
Question: How do I see my monthly active users in Watson Assistant?
Answer: To see your Monthly Active Users do the following:
Login to https://cloud.ibm.com
Click on the Manage menu
Then click on Billing and Usage menu
Click on Usage
For Watson Assistant select View Plans
Under Time Frame Select the month you need
Select your Plus Plan's or Plus Trial plans
There you will see the api calls per month and also Monthly Active Users

**Comment by crlordan** [comment]
FAQ document updated: https://cloud.ibm.com/docs/assistant?topic=assistant-faqs

**Comment by crlordan** [comment]
utterances updated also.
