### ISSUE TITLE
Need to Change Backing up a skill from Export to Download

### ISSUE THREAD

**Issue by miltatibm** [ibm-cloud-docs/assistant#407]
The new menu for exporting a skill is to download not export
https://cloud.ibm.com/docs/assistant?topic=assistant-backup

<img width="204" alt="image" src="https://user-images.githubusercontent.com/19805201/128423452-ef8832ef-de8f-483c-8e8c-9693dee3d51e.png">

**Comment by crlordan** [comment]
Topic is now updated. There were several other term and step changes that weren't accurate as well.

https://cloud.ibm.com/docs/assistant?topic=assistant-backup
