### ISSUE TITLE
Link to IBM Cloud Activity Tracker does not work

### ISSUE THREAD

**Issue by robertocelestino** [ibm-cloud-docs/assistant#413]
Hi, team. 
I'm at the Activity Tracker events page on WA documentation (https://cloud.ibm.com/docs/assistant?topic=assistant-at-events). At the end of the second paragraph, there is a link to IBM Cloud Activity Tracker, which seems to be a get started tutorial, but the link leads to nowhere. 
Tks 

![image](https://user-images.githubusercontent.com/22433095/150339123-1a723e2d-1c0a-41f7-adeb-e07f905d7a79.png)

**Comment by crlordan** [comment]
The link has been fixed.
