### ISSUE TITLE
Need to Specify that Viewer Role to the Resource Group is Required When Selecting Speech Services

### ISSUE THREAD

**Issue by miltatibm** [ibm-cloud-docs/assistant#421]
https://cloud.ibm.com/docs/assistant?topic=assistant-deploy-phone

Please add that Viewer Role to the Resource Group is required when selecting Speech Services. Otherwise a 403 error will occur

**Comment by miltatibm** [comment]
@rrberry FYI Thanks!

**Comment by miltatibm** [comment]
@rrberry but that's not enough they need viewer role to the Resource group

**Comment by californiakat** [comment]
docs were updated with that info already and moved to https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-deploy-phone
