### ISSUE TITLE
Need to be clear on what formats are supported for reformat datetime

### ISSUE THREAD

**Issue by miltatibm** [ibm-cloud-docs/assistant#424]
@rrberry 
In this doc https://cloud.ibm.com/docs/assistant?topic=assistant-dialog-methods#dialog-methods-dates-reformatDateTime

We need to document what formats are supported per this gh https://github.ibm.com/watson-engagement-advisor/wea-backlog/issues/54909#issuecomment-45791870

    Time only: HH:mm:ss or HH:mm
    Date only: yyyy-MM-dd
    DateTime: yyyy-MM-dd HH:mm:ss
    DateTime with timezone: yyyy-MM-dd HH:mm:ss VV (VV comes from the new DateTimeFormatter and represents timezone in IANA Time Zone Database (TZDB) format e.g. Europe/London)

**Comment by californiakat** [comment]
docs have already been updated with this info and now live at https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-dialog-methods#dialog-methods-date-time
